service: express-ALB

custom:
  vpc:
    defaultVpcId: vpc-02babb95598ebd55b
    defaultSecurityGroup: sg-02f592e8908c5e3de
    defaultSubnetId1: subnet-00958fd8a47071819
    defaultSubnetId2: subnet-04e72b8e35800515c
    defaultCidr: 172.31.16.0/20

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-south-1'}
  deploymentBucket:
    name: serverless-deployment-bucket-backend
  ecr:
    images:
      express-ALB:
        path: ./app-express/
        file: Dockerfile

resources:
  Resources:
    SecurityGroup0:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: My Security Group for Express App on Fargate
        VpcId: ${self:custom.vpc.defaultVpcId}
        SecurityGroupIngress:
          - SourceSecurityGroupId: !Ref SecurityGroupALB
            IpProtocol: -1

    SecurityGroupALB:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: My Security Group for ALB
        VpcId: ${self:custom.vpc.defaultVpcId}
        SecurityGroupIngress:
          - CidrIp: 0.0.0.0/0
            IpProtocol: tcp
            FromPort: 80
            ToPort: 80

    ExpressALB:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        Name: ExpressALB
        SecurityGroups:
          - !Ref SecurityGroupALB
        Subnets:
          - ${self:custom.vpc.defaultSubnetId1}
          - ${self:custom.vpc.defaultSubnetId2}
    
    ALBListener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        Protocol: HTTP
        Port: 80
        LoadBalancerArn: !Ref ExpressALB
        DefaultActions:
          - Type: forward
            TargetGroupArn: !Ref ALBTargetGroup

    ALBTargetGroup:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        Port: 8080
        Protocol: HTTP
        TargetType: ip
        VpcId: ${self:custom.vpc.defaultVpcId}

    ExpressECSCluster:
      Type: AWS::ECS::Cluster

    ExpressTaskDefinition:
      Type: AWS::ECS::TaskDefinition
      Properties:
        NetworkMode: awsvpc
        RequiresCompatibilities: 
          - FARGATE
        Cpu: 256
        Memory: 512
        ContainerDefinitions:
          - Name: ExpressContainer
            Image: express-ALB
            PortMappings:
              - ContainerPort: 8080

    ExpressService:
      Type: AWS::ECS::Service
      DependsOn:
        - ALBListener
      Properties:
        Cluster: !Ref ExpressECSCluster
        TaskDefinition: !Ref ExpressTaskDefinition
        LaunchType: FARGATE
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: ENABLED
            Subnets:
              - ${self:custom.vpc.defaultSubnetId1}
            SecurityGroups:
              - !Ref SecurityGroup0
        DesiredCount: 2
        DeploymentConfiguration:
          MaximumPercent: 200
          MinimumHealthyPercent: 100
        LoadBalancers:
          - TargetGroupArn: !Ref ALBTargetGroup
            ContainerName: ExpressContainer
            ContainerPort: 8080
